### ISSUE TITLE
Create webpack loader

### ISSUE THREAD

**Issue by Zip753** [sourceboat/pug-lint-vue#5]
Hi, thanks for making this tool! It would be very cool to have a webpack loader for `*.vue` files that would lint pug templates.

There's been an effort to make a loader like this: [`pug-lint-loader`](https://github.com/Jack-Works/pug-lint-loader). However, it doesn't seem to work with `*.vue` files, only with plain `*.pug`/`*.jade` files.

**Comment by pehbehbeh** [comment]
This project is not actively maintained anymore. See README for more info.
