### ISSUE TITLE
Line numbers are wrong

### ISSUE THREAD

**Issue by mat813** [sourceboat/pug-lint-vue#55]
Say I get this:

```
assets/vue/admin-bank-create.vue
  38:1  Invalid indentation
  49:1  Invalid indentation
  59:1  Invalid indentation
```

The problem is that all my templates are after the scripts, so in this file, the `<template>` tag is on line 262, and the first invalid indentation is in fact on line 299, not 38.

**Comment by pehbehbeh** [comment]
Yes, you are right - we are not adding a line offset here. We will be accepting PRs for this, as I am not able to fix this anytime soon. For some inspiration: We already did this for `sass-lint-vue` (see https://github.com/sourceboat/sass-lint-vue/commit/3d3c223f5debe65e7e5aed0c3faa9e68bb168d73) which is structured very similar.

**Comment by lehni** [comment]
I've had this fixed two years ago but never got around to write a PR for it. Doing so now.
