### ISSUE TITLE
Doesn't support v-bind (and possibly v-on) shorthand

### ISSUE THREAD

**Issue by danherd** [sourceboat/pug-lint-vue#7]
This lints fine:

```
el-form.inline(
  v-bind:model='form'
  v-bind:rules='rules'
  v-bind:ref='formName'
  method='post'
  action=''
  label-position='top'
  status-icon
  v-on:submit.native.prevent='submitForm($event)'
  novalidate
)
```

This throws an 'Unexpected token' error at the line containing the ':rules' parameter (oddly enough, the previous line with the ':model' parameter is fine)

```
el-form.inline(
  :model='form'
  :rules='rules'
  :ref='formName'
  method='post'
  action=''
  label-position='top'
  status-icon
  @submit.native.prevent='submitForm($event)'
  novalidate
)
```

Is this an issue with pug-lint itself, or is it something you can affect with this package?

Cheers!

**Comment by aminimalanimal** [comment]
I've opened [a ticket in the pug-lint repo](https://github.com/pugjs/pug-lint/issues/159) for this. I believe that it is related directly to pug-lint, since I was receiving these syntax errors when running pug-lint itself.

**Comment by Shinigami92** [comment]
Omg, I think I found the problem ...
Since we do not use a comma to split the attributes, pug assumes that it's JavaScript syntax
So if we split the attributes with a comma, the syntax error is gone

... took me some hours ...

**Comment by aminimalanimal** [comment]
This issue was prematurely closed—there shouldn't be a need to add commas to each line. The good folks at `pug-lint` found the underlying issue and the above PR should take care of it. :)

**Comment by pehbehbeh** [comment]
Will be fixed in next release.
