### ISSUE TITLE
Non-Sense Error

### ISSUE THREAD

**Issue by DarkSuniuM** [sourceboat/pug-lint-vue#8]
There is weird error

![Image of Error](https://i.imgur.com/amsJdaV.png)

Error will gone where I change `<label for="fullname">Name:</label>` to `<label for="fullname">Name</label>` ( colons deleted ) or `<label for="fullname">Name: </label>` ( space added ) or even `<label for="fullname">Name :</label>`

It's too weird for me
I think it's a bug

**Comment by krns** [comment]
Thanks for you report.

Have you tried to change your `lang` attribute of you template to `html`?

**Comment by DarkSuniuM** [comment]
Yes, seems like it works well with `lang="html"`
But shouldn't I set `lang` to `pug`?

**Comment by krns** [comment]
It should only set to `pug` if you use pug as your template language like:
```
<template lang="pug">
.container
  .row
      h4.text-center Lorem ipsum
</template>
```
